server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-catalogo
          uri: lb://catalogo-service
          predicates:
            - Path=/produtos/**
          filters:
            - name: AuthenticationFilter
        - id: api-solicitacao
          uri: lb://api-solicitacao
          predicates:
            - Path=/solicitacao/**
          filters:
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.dio.challenge: DEBUG
    org.springframework.cloud.gateway: DEBUG
