server:
  port: 8200

spring:
  application:
    name: api-solicitacao

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      catalogo-service:
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    com.dio.challenge: DEBUG
    org.springframework.cloud: DEBUG
